name: Angular Vitest CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup Node.js
      uses: actions/setup-node@v7
      with:
        node-on-version: '24'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Vitest Tests
      run: npm run test -- --watch=false
      env:
        CI: true